language: node_js
node_js:
  - '8'
  - '10'
env:
  - NODE_OPTIONS=
  - NODE_OPTIONS=--experimental-modules
matrix:
  exclude:
  - node_js: '8'
    env: NODE_OPTIONS=--experimental-modules
deploy:
  - provider: script
    script: npx nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: '10'
before_install:
  - npm i -g npm@^6
